name: Run tests and deploy.

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install ca-certificates and https for apt
      run: |
        sudo apt update
        sudo apt install -y bash curl nodejs npm build-essential git cmake pkg-config \
          libbz2-dev libstxxl-dev libstxxl1v5 libxml2-dev \
          libzip-dev libboost-all-dev lua5.2 liblua5.2-dev libtbb-dev 
# \
# libluabind-dev libluabind0.9.1v5

    - name: Run OSRM tests
      run: |
        pwd
        ls
        ./run_test.sh

    - name: Push librairie to gemfury if branch is master
      run: ./deploy.sh
      env:
        GEMFURY_DEPLOY_TOKEN: ${{ secrets.GEMFURY_DEPLOY_TOKEN }}
        GEMFURY_PUSH_TOKEN: ${{ secrets.GEMFURY_PUSH_TOKEN }}
        GEMFURY_USERNAME: ${{ secrets.GEMFURY_USERNAME }}
